/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* C:\Program Files\Lattice\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n fifo_dc_efb -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type ebfifo -depth 1024 -width 34 -rwidth 34 -no_enable -pe 0 -pf 0  */
/* Sun Aug 25 10:58:03 2019 */


`timescale 1 ns / 1 ps
module fifo_dc_efb (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset,
    AmEmptyThresh, AmFullThresh, Q, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [33:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    input wire [9:0] AmEmptyThresh;
    input wire [9:0] AmFullThresh;
    output wire [33:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire invout_1;
    wire invout_0;
    wire w_g2b_xor_cluster_2;
    wire w_g2b_xor_cluster_1;
    wire r_g2b_xor_cluster_2;
    wire r_g2b_xor_cluster_1;
    wire rcnt_reg_9_inv;
    wire w_gdata_0;
    wire w_gdata_1;
    wire w_gdata_2;
    wire w_gdata_3;
    wire w_gdata_4;
    wire w_gdata_5;
    wire w_gdata_6;
    wire w_gdata_7;
    wire w_gdata_8;
    wire w_gdata_9;
    wire wptr_0;
    wire wptr_1;
    wire wptr_2;
    wire wptr_3;
    wire wptr_4;
    wire wptr_5;
    wire wptr_6;
    wire wptr_7;
    wire wptr_8;
    wire wptr_9;
    wire wptr_10;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire r_gdata_5;
    wire r_gdata_6;
    wire r_gdata_7;
    wire r_gdata_8;
    wire r_gdata_9;
    wire rptr_0;
    wire rptr_1;
    wire rptr_2;
    wire rptr_3;
    wire rptr_4;
    wire rptr_5;
    wire rptr_6;
    wire rptr_7;
    wire rptr_8;
    wire rptr_9;
    wire rptr_10;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire w_gcount_3;
    wire w_gcount_4;
    wire w_gcount_5;
    wire w_gcount_6;
    wire w_gcount_7;
    wire w_gcount_8;
    wire w_gcount_9;
    wire w_gcount_10;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire r_gcount_6;
    wire r_gcount_7;
    wire r_gcount_8;
    wire r_gcount_9;
    wire r_gcount_10;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire w_gcount_r23;
    wire w_gcount_r3;
    wire w_gcount_r24;
    wire w_gcount_r4;
    wire w_gcount_r25;
    wire w_gcount_r5;
    wire w_gcount_r26;
    wire w_gcount_r6;
    wire w_gcount_r27;
    wire w_gcount_r7;
    wire w_gcount_r28;
    wire w_gcount_r8;
    wire w_gcount_r29;
    wire w_gcount_r9;
    wire w_gcount_r210;
    wire w_gcount_r10;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire r_gcount_w26;
    wire r_gcount_w6;
    wire r_gcount_w27;
    wire r_gcount_w7;
    wire r_gcount_w28;
    wire r_gcount_w8;
    wire r_gcount_w29;
    wire r_gcount_w9;
    wire r_gcount_w210;
    wire r_gcount_w10;
    wire rcnt_reg_10;
    wire empty_i;
    wire full_i;
    wire rRst;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire iwcount_3;
    wire co0;
    wire iwcount_4;
    wire iwcount_5;
    wire co1;
    wire iwcount_6;
    wire iwcount_7;
    wire co2;
    wire iwcount_8;
    wire iwcount_9;
    wire co3;
    wire iwcount_10;
    wire co5;
    wire co4;
    wire wcount_10;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co1_1;
    wire ircount_6;
    wire ircount_7;
    wire co2_1;
    wire ircount_8;
    wire ircount_9;
    wire co3_1;
    wire ircount_10;
    wire co5_1;
    wire co4_1;
    wire rcount_10;
    wire wcnt_sub_0;
    wire precin;
    wire wcnt_sub_1;
    wire wcnt_sub_2;
    wire co0_2;
    wire wcnt_sub_3;
    wire wcnt_sub_4;
    wire co1_2;
    wire wcnt_sub_5;
    wire wcnt_sub_6;
    wire co2_2;
    wire wcnt_sub_7;
    wire wcnt_sub_8;
    wire co3_2;
    wire wcnt_sub_9;
    wire wcnt_sub_10;
    wire co4_2;
    wire wcnt_sub_msb;
    wire co5_2d;
    wire co5_2;
    wire rcnt_sub_0;
    wire precin_1;
    wire scuba_vhi;
    wire rcnt_sub_1;
    wire rcnt_sub_2;
    wire co0_3;
    wire rcnt_sub_3;
    wire rcnt_sub_4;
    wire co1_3;
    wire rcnt_sub_5;
    wire rcnt_sub_6;
    wire co2_3;
    wire rcnt_sub_7;
    wire rcnt_sub_8;
    wire co3_3;
    wire rcnt_sub_9;
    wire rcnt_sub_10;
    wire co4_3;
    wire rcnt_sub_msb;
    wire co5_3d;
    wire co5_3;
    wire cmp_ci;
    wire wcount_r0;
    wire wcount_r1;
    wire rcount_0;
    wire rcount_1;
    wire co0_4;
    wire wcount_r2;
    wire wcount_r3;
    wire rcount_2;
    wire rcount_3;
    wire co1_4;
    wire wcount_r4;
    wire wcount_r5;
    wire rcount_4;
    wire rcount_5;
    wire co2_4;
    wire wcount_r6;
    wire w_g2b_xor_cluster_0;
    wire rcount_6;
    wire rcount_7;
    wire co3_4;
    wire wcount_r8;
    wire wcount_r9;
    wire rcount_8;
    wire rcount_9;
    wire co4_4;
    wire empty_cmp_clr;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire cmp_ci_1;
    wire rcount_w0;
    wire rcount_w1;
    wire wcount_0;
    wire wcount_1;
    wire co0_5;
    wire rcount_w2;
    wire rcount_w3;
    wire wcount_2;
    wire wcount_3;
    wire co1_5;
    wire rcount_w4;
    wire rcount_w5;
    wire wcount_4;
    wire wcount_5;
    wire co2_5;
    wire rcount_w6;
    wire r_g2b_xor_cluster_0;
    wire wcount_6;
    wire wcount_7;
    wire co3_5;
    wire rcount_w8;
    wire rcount_w9;
    wire wcount_8;
    wire wcount_9;
    wire co4_5;
    wire full_cmp_clr;
    wire full_cmp_set;
    wire full_d;
    wire full_d_c;
    wire rden_i;
    wire cmp_ci_2;
    wire rcnt_reg_0;
    wire rcnt_reg_1;
    wire co0_6;
    wire rcnt_reg_2;
    wire rcnt_reg_3;
    wire co1_6;
    wire rcnt_reg_4;
    wire rcnt_reg_5;
    wire co2_6;
    wire rcnt_reg_6;
    wire rcnt_reg_7;
    wire co3_6;
    wire rcnt_reg_8;
    wire rcnt_reg_9;
    wire co4_6;
    wire ae_clrsig;
    wire ae_setsig;
    wire ae_d;
    wire ae_d_c;
    wire wren_i;
    wire cmp_ci_3;
    wire wcnt_reg_0;
    wire wcnt_reg_1;
    wire co0_7;
    wire wcnt_reg_2;
    wire wcnt_reg_3;
    wire co1_7;
    wire wcnt_reg_4;
    wire wcnt_reg_5;
    wire co2_7;
    wire wcnt_reg_6;
    wire wcnt_reg_7;
    wire co3_7;
    wire wcnt_reg_8;
    wire wcnt_reg_9;
    wire co4_7;
    wire wcnt_reg_10;
    wire af_d;
    wire af_d_c;
    wire scuba_vlo;

    AND2 AND2_t26 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_2 (.A(full_i), .Z(invout_1));

    AND2 AND2_t25 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_1 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t24 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t23 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t22 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t21 (.A(wcount_2), .B(wcount_3), .Z(w_gdata_2));

    XOR2 XOR2_t20 (.A(wcount_3), .B(wcount_4), .Z(w_gdata_3));

    XOR2 XOR2_t19 (.A(wcount_4), .B(wcount_5), .Z(w_gdata_4));

    XOR2 XOR2_t18 (.A(wcount_5), .B(wcount_6), .Z(w_gdata_5));

    XOR2 XOR2_t17 (.A(wcount_6), .B(wcount_7), .Z(w_gdata_6));

    XOR2 XOR2_t16 (.A(wcount_7), .B(wcount_8), .Z(w_gdata_7));

    XOR2 XOR2_t15 (.A(wcount_8), .B(wcount_9), .Z(w_gdata_8));

    XOR2 XOR2_t14 (.A(wcount_9), .B(wcount_10), .Z(w_gdata_9));

    XOR2 XOR2_t13 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t12 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t11 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t10 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t9 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    XOR2 XOR2_t8 (.A(rcount_5), .B(rcount_6), .Z(r_gdata_5));

    XOR2 XOR2_t7 (.A(rcount_6), .B(rcount_7), .Z(r_gdata_6));

    XOR2 XOR2_t6 (.A(rcount_7), .B(rcount_8), .Z(r_gdata_7));

    XOR2 XOR2_t5 (.A(rcount_8), .B(rcount_9), .Z(r_gdata_8));

    XOR2 XOR2_t4 (.A(rcount_9), .B(rcount_10), .Z(r_gdata_9));

    defparam LUT4_27.initval =  16'h6996 ;
    ROM16X1A LUT4_27 (.AD3(w_gcount_r27), .AD2(w_gcount_r28), .AD1(w_gcount_r29),
        .AD0(w_gcount_r210), .DO0(w_g2b_xor_cluster_0));

    defparam LUT4_26.initval =  16'h6996 ;
    ROM16X1A LUT4_26 (.AD3(w_gcount_r23), .AD2(w_gcount_r24), .AD1(w_gcount_r25),
        .AD0(w_gcount_r26), .DO0(w_g2b_xor_cluster_1));

    defparam LUT4_25.initval =  16'h6996 ;
    ROM16X1A LUT4_25 (.AD3(w_gcount_r29), .AD2(w_gcount_r210), .AD1(scuba_vlo),
        .AD0(scuba_vlo), .DO0(wcount_r9));

    defparam LUT4_24.initval =  16'h6996 ;
    ROM16X1A LUT4_24 (.AD3(w_gcount_r28), .AD2(w_gcount_r29), .AD1(w_gcount_r210),
        .AD0(scuba_vlo), .DO0(wcount_r8));

    defparam LUT4_23.initval =  16'h6996 ;
    ROM16X1A LUT4_23 (.AD3(w_gcount_r26), .AD2(w_gcount_r27), .AD1(w_gcount_r28),
        .AD0(wcount_r9), .DO0(wcount_r6));

    defparam LUT4_22.initval =  16'h6996 ;
    ROM16X1A LUT4_22 (.AD3(w_gcount_r25), .AD2(w_gcount_r26), .AD1(w_gcount_r27),
        .AD0(wcount_r8), .DO0(wcount_r5));

    defparam LUT4_21.initval =  16'h6996 ;
    ROM16X1A LUT4_21 (.AD3(w_gcount_r24), .AD2(w_gcount_r25), .AD1(w_gcount_r26),
        .AD0(w_g2b_xor_cluster_0), .DO0(wcount_r4));

    defparam LUT4_20.initval =  16'h6996 ;
    ROM16X1A LUT4_20 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1),
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(wcount_r3));

    defparam LUT4_19.initval =  16'h6996 ;
    ROM16X1A LUT4_19 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1),
        .AD1(w_gcount_r22), .AD0(scuba_vlo), .DO0(wcount_r2));

    defparam LUT4_18.initval =  16'h6996 ;
    ROM16X1A LUT4_18 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1),
        .AD1(w_gcount_r21), .AD0(w_gcount_r22), .DO0(wcount_r1));

    defparam LUT4_17.initval =  16'h6996 ;
    ROM16X1A LUT4_17 (.AD3(w_gcount_r20), .AD2(w_gcount_r21), .AD1(w_gcount_r22),
        .AD0(scuba_vlo), .DO0(w_g2b_xor_cluster_2));

    defparam LUT4_16.initval =  16'h6996 ;
    ROM16X1A LUT4_16 (.AD3(w_g2b_xor_cluster_0), .AD2(w_g2b_xor_cluster_1),
        .AD1(w_g2b_xor_cluster_2), .AD0(scuba_vlo), .DO0(wcount_r0));

    defparam LUT4_15.initval =  16'h6996 ;
    ROM16X1A LUT4_15 (.AD3(r_gcount_w27), .AD2(r_gcount_w28), .AD1(r_gcount_w29),
        .AD0(r_gcount_w210), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_14.initval =  16'h6996 ;
    ROM16X1A LUT4_14 (.AD3(r_gcount_w23), .AD2(r_gcount_w24), .AD1(r_gcount_w25),
        .AD0(r_gcount_w26), .DO0(r_g2b_xor_cluster_1));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(r_gcount_w29), .AD2(r_gcount_w210), .AD1(scuba_vlo),
        .AD0(scuba_vlo), .DO0(rcount_w9));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(r_gcount_w28), .AD2(r_gcount_w29), .AD1(r_gcount_w210),
        .AD0(scuba_vlo), .DO0(rcount_w8));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(r_gcount_w26), .AD2(r_gcount_w27), .AD1(r_gcount_w28),
        .AD0(rcount_w9), .DO0(rcount_w6));

    defparam LUT4_10.initval =  16'h6996 ;
    ROM16X1A LUT4_10 (.AD3(r_gcount_w25), .AD2(r_gcount_w26), .AD1(r_gcount_w27),
        .AD0(rcount_w8), .DO0(rcount_w5));

    defparam LUT4_9.initval =  16'h6996 ;
    ROM16X1A LUT4_9 (.AD3(r_gcount_w24), .AD2(r_gcount_w25), .AD1(r_gcount_w26),
        .AD0(r_g2b_xor_cluster_0), .DO0(rcount_w4));

    defparam LUT4_8.initval =  16'h6996 ;
    ROM16X1A LUT4_8 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1),
        .AD1(scuba_vlo), .AD0(scuba_vlo), .DO0(rcount_w3));

    defparam LUT4_7.initval =  16'h6996 ;
    ROM16X1A LUT4_7 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1),
        .AD1(r_gcount_w22), .AD0(scuba_vlo), .DO0(rcount_w2));

    defparam LUT4_6.initval =  16'h6996 ;
    ROM16X1A LUT4_6 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1),
        .AD1(r_gcount_w21), .AD0(r_gcount_w22), .DO0(rcount_w1));

    defparam LUT4_5.initval =  16'h6996 ;
    ROM16X1A LUT4_5 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(r_gcount_w22),
        .AD0(scuba_vlo), .DO0(r_g2b_xor_cluster_2));

    defparam LUT4_4.initval =  16'h6996 ;
    ROM16X1A LUT4_4 (.AD3(r_g2b_xor_cluster_0), .AD2(r_g2b_xor_cluster_1),
        .AD1(r_g2b_xor_cluster_2), .AD0(scuba_vlo), .DO0(rcount_w0));

    XOR2 XOR2_t3 (.A(wcount_10), .B(r_gcount_w210), .Z(wcnt_sub_msb));

    XOR2 XOR2_t2 (.A(w_gcount_r210), .B(rcount_10), .Z(rcnt_sub_msb));

    defparam LUT4_3.initval =  16'h0410 ;
    ROM16X1A LUT4_3 (.AD3(rptr_10), .AD2(rcount_10), .AD1(w_gcount_r210),
        .AD0(scuba_vlo), .DO0(empty_cmp_set));

    defparam LUT4_2.initval =  16'h1004 ;
    ROM16X1A LUT4_2 (.AD3(rptr_10), .AD2(rcount_10), .AD1(w_gcount_r210),
        .AD0(scuba_vlo), .DO0(empty_cmp_clr));

    defparam LUT4_1.initval =  16'h0140 ;
    ROM16X1A LUT4_1 (.AD3(wptr_10), .AD2(wcount_10), .AD1(r_gcount_w210),
        .AD0(scuba_vlo), .DO0(full_cmp_set));

    defparam LUT4_0.initval =  16'h4001 ;
    ROM16X1A LUT4_0 (.AD3(wptr_10), .AD2(wcount_10), .AD1(r_gcount_w210),
        .AD0(scuba_vlo), .DO0(full_cmp_clr));

    INV INV_0 (.A(rcnt_reg_9), .Z(rcnt_reg_9_inv));

    AND2 AND2_t1 (.A(rcnt_reg_10), .B(rcnt_reg_9_inv), .Z(ae_clrsig));

    AND2 AND2_t0 (.A(rcnt_reg_10), .B(rcnt_reg_9), .Z(ae_setsig));

    defparam pdp_ram_0_0_3.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_0_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_0_3.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_0_3.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_0_3.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_0_3.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_0_3.GSR = "ENABLED" ;
    defparam pdp_ram_0_0_3.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_0_3.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_0_3.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_0_3.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_0_0_3.DATA_WIDTH_A = 9 ;
    DP8KC pdp_ram_0_0_3 (.DIA8(Data[8]), .DIA7(Data[7]), .DIA6(Data[6]),
        .DIA5(Data[5]), .DIA4(Data[4]), .DIA3(Data[3]), .DIA2(Data[2]),
        .DIA1(Data[1]), .DIA0(Data[0]), .ADA12(wptr_9), .ADA11(wptr_8),
        .ADA10(wptr_7), .ADA9(wptr_6), .ADA8(wptr_5), .ADA7(wptr_4), .ADA6(wptr_3),
        .ADA5(wptr_2), .ADA4(wptr_1), .ADA3(wptr_0), .ADA2(scuba_vlo), .ADA1(scuba_vlo),
        .ADA0(scuba_vhi), .CEA(wren_i), .OCEA(wren_i), .CLKA(WrClock), .WEA(scuba_vhi),
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset),
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo),
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo),
        .DIB0(scuba_vlo), .ADB12(rptr_9), .ADB11(rptr_8), .ADB10(rptr_7),
        .ADB9(rptr_6), .ADB8(rptr_5), .ADB7(rptr_4), .ADB6(rptr_3), .ADB5(rptr_2),
        .ADB4(rptr_1), .ADB3(rptr_0), .ADB2(scuba_vlo), .ADB1(scuba_vlo),
        .ADB0(scuba_vlo), .CEB(rden_i), .OCEB(rden_i), .CLKB(RdClock), .WEB(scuba_vlo),
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset),
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(),
        .DOA0(), .DOB8(Q[8]), .DOB7(Q[7]), .DOB6(Q[6]), .DOB5(Q[5]), .DOB4(Q[4]),
        .DOB3(Q[3]), .DOB2(Q[2]), .DOB1(Q[1]), .DOB0(Q[0]))
             /* synthesis MEM_LPC_FILE="fifo_dc_efb.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_1_2.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_1_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_1_2.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_1_2.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_1_2.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_1_2.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_1_2.GSR = "ENABLED" ;
    defparam pdp_ram_0_1_2.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_1_2.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_1_2.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_1_2.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_0_1_2.DATA_WIDTH_A = 9 ;
    DP8KC pdp_ram_0_1_2 (.DIA8(Data[17]), .DIA7(Data[16]), .DIA6(Data[15]),
        .DIA5(Data[14]), .DIA4(Data[13]), .DIA3(Data[12]), .DIA2(Data[11]),
        .DIA1(Data[10]), .DIA0(Data[9]), .ADA12(wptr_9), .ADA11(wptr_8),
        .ADA10(wptr_7), .ADA9(wptr_6), .ADA8(wptr_5), .ADA7(wptr_4), .ADA6(wptr_3),
        .ADA5(wptr_2), .ADA4(wptr_1), .ADA3(wptr_0), .ADA2(scuba_vlo), .ADA1(scuba_vlo),
        .ADA0(scuba_vhi), .CEA(wren_i), .OCEA(wren_i), .CLKA(WrClock), .WEA(scuba_vhi),
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset),
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo),
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo),
        .DIB0(scuba_vlo), .ADB12(rptr_9), .ADB11(rptr_8), .ADB10(rptr_7),
        .ADB9(rptr_6), .ADB8(rptr_5), .ADB7(rptr_4), .ADB6(rptr_3), .ADB5(rptr_2),
        .ADB4(rptr_1), .ADB3(rptr_0), .ADB2(scuba_vlo), .ADB1(scuba_vlo),
        .ADB0(scuba_vlo), .CEB(rden_i), .OCEB(rden_i), .CLKB(RdClock), .WEB(scuba_vlo),
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset),
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(),
        .DOA0(), .DOB8(Q[17]), .DOB7(Q[16]), .DOB6(Q[15]), .DOB5(Q[14]),
        .DOB4(Q[13]), .DOB3(Q[12]), .DOB2(Q[11]), .DOB1(Q[10]), .DOB0(Q[9]))
             /* synthesis MEM_LPC_FILE="fifo_dc_efb.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_2_1.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_2_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_2_1.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_2_1.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_2_1.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_2_1.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_2_1.GSR = "ENABLED" ;
    defparam pdp_ram_0_2_1.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_2_1.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_2_1.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_2_1.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_0_2_1.DATA_WIDTH_A = 9 ;
    DP8KC pdp_ram_0_2_1 (.DIA8(Data[26]), .DIA7(Data[25]), .DIA6(Data[24]),
        .DIA5(Data[23]), .DIA4(Data[22]), .DIA3(Data[21]), .DIA2(Data[20]),
        .DIA1(Data[19]), .DIA0(Data[18]), .ADA12(wptr_9), .ADA11(wptr_8),
        .ADA10(wptr_7), .ADA9(wptr_6), .ADA8(wptr_5), .ADA7(wptr_4), .ADA6(wptr_3),
        .ADA5(wptr_2), .ADA4(wptr_1), .ADA3(wptr_0), .ADA2(scuba_vlo), .ADA1(scuba_vlo),
        .ADA0(scuba_vhi), .CEA(wren_i), .OCEA(wren_i), .CLKA(WrClock), .WEA(scuba_vhi),
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset),
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo),
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo),
        .DIB0(scuba_vlo), .ADB12(rptr_9), .ADB11(rptr_8), .ADB10(rptr_7),
        .ADB9(rptr_6), .ADB8(rptr_5), .ADB7(rptr_4), .ADB6(rptr_3), .ADB5(rptr_2),
        .ADB4(rptr_1), .ADB3(rptr_0), .ADB2(scuba_vlo), .ADB1(scuba_vlo),
        .ADB0(scuba_vlo), .CEB(rden_i), .OCEB(rden_i), .CLKB(RdClock), .WEB(scuba_vlo),
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset),
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(),
        .DOA0(), .DOB8(Q[26]), .DOB7(Q[25]), .DOB6(Q[24]), .DOB5(Q[23]),
        .DOB4(Q[22]), .DOB3(Q[21]), .DOB2(Q[20]), .DOB1(Q[19]), .DOB0(Q[18]))
             /* synthesis MEM_LPC_FILE="fifo_dc_efb.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    defparam pdp_ram_0_3_0.INIT_DATA = "STATIC" ;
    defparam pdp_ram_0_3_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam pdp_ram_0_3_0.CSDECODE_B = "0b000" ;
    defparam pdp_ram_0_3_0.CSDECODE_A = "0b000" ;
    defparam pdp_ram_0_3_0.WRITEMODE_B = "NORMAL" ;
    defparam pdp_ram_0_3_0.WRITEMODE_A = "NORMAL" ;
    defparam pdp_ram_0_3_0.GSR = "ENABLED" ;
    defparam pdp_ram_0_3_0.RESETMODE = "ASYNC" ;
    defparam pdp_ram_0_3_0.REGMODE_B = "NOREG" ;
    defparam pdp_ram_0_3_0.REGMODE_A = "NOREG" ;
    defparam pdp_ram_0_3_0.DATA_WIDTH_B = 9 ;
    defparam pdp_ram_0_3_0.DATA_WIDTH_A = 9 ;
    DP8KC pdp_ram_0_3_0 (.DIA8(scuba_vlo), .DIA7(scuba_vlo), .DIA6(Data[33]),
        .DIA5(Data[32]), .DIA4(Data[31]), .DIA3(Data[30]), .DIA2(Data[29]),
        .DIA1(Data[28]), .DIA0(Data[27]), .ADA12(wptr_9), .ADA11(wptr_8),
        .ADA10(wptr_7), .ADA9(wptr_6), .ADA8(wptr_5), .ADA7(wptr_4), .ADA6(wptr_3),
        .ADA5(wptr_2), .ADA4(wptr_1), .ADA3(wptr_0), .ADA2(scuba_vlo), .ADA1(scuba_vlo),
        .ADA0(scuba_vhi), .CEA(wren_i), .OCEA(wren_i), .CLKA(WrClock), .WEA(scuba_vhi),
        .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset),
        .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo),
        .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo),
        .DIB0(scuba_vlo), .ADB12(rptr_9), .ADB11(rptr_8), .ADB10(rptr_7),
        .ADB9(rptr_6), .ADB8(rptr_5), .ADB7(rptr_4), .ADB6(rptr_3), .ADB5(rptr_2),
        .ADB4(rptr_1), .ADB3(rptr_0), .ADB2(scuba_vlo), .ADB1(scuba_vlo),
        .ADB0(scuba_vlo), .CEB(rden_i), .OCEB(rden_i), .CLKB(RdClock), .WEB(scuba_vlo),
        .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), .RSTB(Reset),
        .DOA8(), .DOA7(), .DOA6(), .DOA5(), .DOA4(), .DOA3(), .DOA2(), .DOA1(),
        .DOA0(), .DOB8(), .DOB7(), .DOB6(Q[33]), .DOB5(Q[32]), .DOB4(Q[31]),
        .DOB3(Q[30]), .DOB2(Q[29]), .DOB1(Q[28]), .DOB0(Q[27]))
             /* synthesis MEM_LPC_FILE="fifo_dc_efb.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3BX FF_135 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset),
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_134 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_133 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_132 (.D(iwcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_131 (.D(iwcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_130 (.D(iwcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_129 (.D(iwcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_128 (.D(iwcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_127 (.D(iwcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_126 (.D(iwcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_125 (.D(iwcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_124 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_123 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_122 (.D(w_gdata_2), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_121 (.D(w_gdata_3), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_120 (.D(w_gdata_4), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_119 (.D(w_gdata_5), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_118 (.D(w_gdata_6), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_117 (.D(w_gdata_7), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_116 (.D(w_gdata_8), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_115 (.D(w_gdata_9), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_114 (.D(wcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(w_gcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_113 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_112 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_111 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_110 (.D(wcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_109 (.D(wcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_108 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_107 (.D(wcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_106 (.D(wcount_7), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_105 (.D(wcount_8), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_104 (.D(wcount_9), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_103 (.D(wcount_10), .SP(wren_i), .CK(WrClock), .CD(Reset),
        .Q(wptr_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_102 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst),
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_101 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_100 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_99 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_98 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_97 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_96 (.D(ircount_6), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_95 (.D(ircount_7), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_94 (.D(ircount_8), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_93 (.D(ircount_9), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_92 (.D(ircount_10), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_91 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_90 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_89 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_88 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_87 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_86 (.D(r_gdata_5), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_85 (.D(r_gdata_6), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_84 (.D(r_gdata_7), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_83 (.D(r_gdata_8), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_82 (.D(r_gdata_9), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_81 (.D(rcount_10), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(r_gcount_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_80 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_79 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_78 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_77 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_76 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_75 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_74 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_73 (.D(rcount_7), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(rcount_8), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(rcount_9), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(rcount_10), .SP(rden_i), .CK(RdClock), .CD(rRst),
        .Q(rptr_10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_69 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_68 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_67 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_66 (.D(w_gcount_3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_65 (.D(w_gcount_4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_64 (.D(w_gcount_5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_63 (.D(w_gcount_6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_62 (.D(w_gcount_7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_61 (.D(w_gcount_8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_60 (.D(w_gcount_9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_59 (.D(w_gcount_10), .CK(RdClock), .CD(Reset), .Q(w_gcount_r10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_58 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_57 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_56 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_55 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_54 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_53 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_52 (.D(r_gcount_6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_51 (.D(r_gcount_7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_50 (.D(r_gcount_8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_49 (.D(r_gcount_9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_48 (.D(r_gcount_10), .CK(WrClock), .CD(rRst), .Q(r_gcount_w10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_47 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_46 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_45 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_44 (.D(w_gcount_r3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_43 (.D(w_gcount_r4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_42 (.D(w_gcount_r5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_41 (.D(w_gcount_r6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_40 (.D(w_gcount_r7), .CK(RdClock), .CD(Reset), .Q(w_gcount_r27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_39 (.D(w_gcount_r8), .CK(RdClock), .CD(Reset), .Q(w_gcount_r28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_38 (.D(w_gcount_r9), .CK(RdClock), .CD(Reset), .Q(w_gcount_r29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_37 (.D(w_gcount_r10), .CK(RdClock), .CD(Reset), .Q(w_gcount_r210))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_36 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_35 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_34 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_33 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_32 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_31 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_30 (.D(r_gcount_w6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_29 (.D(r_gcount_w7), .CK(WrClock), .CD(rRst), .Q(r_gcount_w27))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_28 (.D(r_gcount_w8), .CK(WrClock), .CD(rRst), .Q(r_gcount_w28))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_27 (.D(r_gcount_w9), .CK(WrClock), .CD(rRst), .Q(r_gcount_w29))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_26 (.D(r_gcount_w10), .CK(WrClock), .CD(rRst), .Q(r_gcount_w210))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_25 (.D(wcnt_sub_0), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_24 (.D(wcnt_sub_1), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_23 (.D(wcnt_sub_2), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_22 (.D(wcnt_sub_3), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_21 (.D(wcnt_sub_4), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_20 (.D(wcnt_sub_5), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_19 (.D(wcnt_sub_6), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_18 (.D(wcnt_sub_7), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_17 (.D(wcnt_sub_8), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_16 (.D(wcnt_sub_9), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_15 (.D(wcnt_sub_10), .CK(WrClock), .CD(Reset), .Q(wcnt_reg_10))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_14 (.D(rcnt_sub_0), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_13 (.D(rcnt_sub_1), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_12 (.D(rcnt_sub_2), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_11 (.D(rcnt_sub_3), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_10 (.D(rcnt_sub_4), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_9 (.D(rcnt_sub_5), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_8 (.D(rcnt_sub_6), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_7 (.D(rcnt_sub_7), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_7))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_6 (.D(rcnt_sub_8), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_8))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_5 (.D(rcnt_sub_9), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_9))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_4 (.D(rcnt_sub_10), .CK(RdClock), .CD(rRst), .Q(rcnt_reg_10))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_3 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_2 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_1 (.D(ae_d), .CK(RdClock), .PD(rRst), .Q(AlmostEmpty))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(af_d), .CK(WrClock), .CD(Reset), .Q(AlmostFull))
             /* synthesis GSR="ENABLED" */;

    FADD2B w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi),
        .CI(scuba_vlo), .COUT(w_gctr_ci), .S0(), .S1());

    CU2 w_gctr_0 (.CI(w_gctr_ci), .PC0(wcount_0), .PC1(wcount_1), .CO(co0),
        .NC0(iwcount_0), .NC1(iwcount_1));

    CU2 w_gctr_1 (.CI(co0), .PC0(wcount_2), .PC1(wcount_3), .CO(co1), .NC0(iwcount_2),
        .NC1(iwcount_3));

    CU2 w_gctr_2 (.CI(co1), .PC0(wcount_4), .PC1(wcount_5), .CO(co2), .NC0(iwcount_4),
        .NC1(iwcount_5));

    CU2 w_gctr_3 (.CI(co2), .PC0(wcount_6), .PC1(wcount_7), .CO(co3), .NC0(iwcount_6),
        .NC1(iwcount_7));

    CU2 w_gctr_4 (.CI(co3), .PC0(wcount_8), .PC1(wcount_9), .CO(co4), .NC0(iwcount_8),
        .NC1(iwcount_9));

    CU2 w_gctr_5 (.CI(co4), .PC0(wcount_10), .PC1(scuba_vlo), .CO(co5),
        .NC0(iwcount_10), .NC1());

    FADD2B r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi),
        .CI(scuba_vlo), .COUT(r_gctr_ci), .S0(), .S1());

    CU2 r_gctr_0 (.CI(r_gctr_ci), .PC0(rcount_0), .PC1(rcount_1), .CO(co0_1),
        .NC0(ircount_0), .NC1(ircount_1));

    CU2 r_gctr_1 (.CI(co0_1), .PC0(rcount_2), .PC1(rcount_3), .CO(co1_1),
        .NC0(ircount_2), .NC1(ircount_3));

    CU2 r_gctr_2 (.CI(co1_1), .PC0(rcount_4), .PC1(rcount_5), .CO(co2_1),
        .NC0(ircount_4), .NC1(ircount_5));

    CU2 r_gctr_3 (.CI(co2_1), .PC0(rcount_6), .PC1(rcount_7), .CO(co3_1),
        .NC0(ircount_6), .NC1(ircount_7));

    CU2 r_gctr_4 (.CI(co3_1), .PC0(rcount_8), .PC1(rcount_9), .CO(co4_1),
        .NC0(ircount_8), .NC1(ircount_9));

    CU2 r_gctr_5 (.CI(co4_1), .PC0(rcount_10), .PC1(scuba_vlo), .CO(co5_1),
        .NC0(ircount_10), .NC1());

    FADD2B precin_inst314 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo),
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(precin), .S0(), .S1());

    FSUB2B wcnt_0 (.A0(scuba_vhi), .A1(wcount_0), .B0(scuba_vlo), .B1(rcount_w0),
        .BI(precin), .BOUT(co0_2), .S0(), .S1(wcnt_sub_0));

    FSUB2B wcnt_1 (.A0(wcount_1), .A1(wcount_2), .B0(rcount_w1), .B1(rcount_w2),
        .BI(co0_2), .BOUT(co1_2), .S0(wcnt_sub_1), .S1(wcnt_sub_2));

    FSUB2B wcnt_2 (.A0(wcount_3), .A1(wcount_4), .B0(rcount_w3), .B1(rcount_w4),
        .BI(co1_2), .BOUT(co2_2), .S0(wcnt_sub_3), .S1(wcnt_sub_4));

    FSUB2B wcnt_3 (.A0(wcount_5), .A1(wcount_6), .B0(rcount_w5), .B1(rcount_w6),
        .BI(co2_2), .BOUT(co3_2), .S0(wcnt_sub_5), .S1(wcnt_sub_6));

    FSUB2B wcnt_4 (.A0(wcount_7), .A1(wcount_8), .B0(r_g2b_xor_cluster_0),
        .B1(rcount_w8), .BI(co3_2), .BOUT(co4_2), .S0(wcnt_sub_7), .S1(wcnt_sub_8));

    FSUB2B wcnt_5 (.A0(wcount_9), .A1(wcnt_sub_msb), .B0(rcount_w9), .B1(scuba_vlo),
        .BI(co4_2), .BOUT(co5_2), .S0(wcnt_sub_9), .S1(wcnt_sub_10));

    FADD2B wcntd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo),
        .CI(co5_2), .COUT(), .S0(co5_2d), .S1());

    FADD2B precin_inst345 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo),
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(precin_1), .S0(), .S1());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FSUB2B rcnt_0 (.A0(scuba_vhi), .A1(wcount_r0), .B0(scuba_vlo), .B1(rcount_0),
        .BI(precin_1), .BOUT(co0_3), .S0(), .S1(rcnt_sub_0));

    FSUB2B rcnt_1 (.A0(wcount_r1), .A1(wcount_r2), .B0(rcount_1), .B1(rcount_2),
        .BI(co0_3), .BOUT(co1_3), .S0(rcnt_sub_1), .S1(rcnt_sub_2));

    FSUB2B rcnt_2 (.A0(wcount_r3), .A1(wcount_r4), .B0(rcount_3), .B1(rcount_4),
        .BI(co1_3), .BOUT(co2_3), .S0(rcnt_sub_3), .S1(rcnt_sub_4));

    FSUB2B rcnt_3 (.A0(wcount_r5), .A1(wcount_r6), .B0(rcount_5), .B1(rcount_6),
        .BI(co2_3), .BOUT(co3_3), .S0(rcnt_sub_5), .S1(rcnt_sub_6));

    FSUB2B rcnt_4 (.A0(w_g2b_xor_cluster_0), .A1(wcount_r8), .B0(rcount_7),
        .B1(rcount_8), .BI(co3_3), .BOUT(co4_3), .S0(rcnt_sub_7), .S1(rcnt_sub_8));

    FSUB2B rcnt_5 (.A0(wcount_r9), .A1(rcnt_sub_msb), .B0(rcount_9), .B1(scuba_vlo),
        .BI(co4_3), .BOUT(co5_3), .S0(rcnt_sub_9), .S1(rcnt_sub_10));

    FADD2B rcntd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo),
        .CI(co5_3), .COUT(), .S0(co5_3d), .S1());

    FADD2B empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo),
        .B1(rden_i), .CI(scuba_vlo), .COUT(cmp_ci), .S0(), .S1());

    AGEB2 empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(wcount_r0), .B1(wcount_r1),
        .CI(cmp_ci), .GE(co0_4));

    AGEB2 empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(wcount_r2), .B1(wcount_r3),
        .CI(co0_4), .GE(co1_4));

    AGEB2 empty_cmp_2 (.A0(rcount_4), .A1(rcount_5), .B0(wcount_r4), .B1(wcount_r5),
        .CI(co1_4), .GE(co2_4));

    AGEB2 empty_cmp_3 (.A0(rcount_6), .A1(rcount_7), .B0(wcount_r6), .B1(w_g2b_xor_cluster_0),
        .CI(co2_4), .GE(co3_4));

    AGEB2 empty_cmp_4 (.A0(rcount_8), .A1(rcount_9), .B0(wcount_r8), .B1(wcount_r9),
        .CI(co3_4), .GE(co4_4));

    AGEB2 empty_cmp_5 (.A0(empty_cmp_set), .A1(scuba_vlo), .B0(empty_cmp_clr),
        .B1(scuba_vlo), .CI(co4_4), .GE(empty_d_c));

    FADD2B a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo),
        .CI(empty_d_c), .COUT(), .S0(empty_d), .S1());

    FADD2B full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i),
        .CI(scuba_vlo), .COUT(cmp_ci_1), .S0(), .S1());

    AGEB2 full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w0), .B1(rcount_w1),
        .CI(cmp_ci_1), .GE(co0_5));

    AGEB2 full_cmp_1 (.A0(wcount_2), .A1(wcount_3), .B0(rcount_w2), .B1(rcount_w3),
        .CI(co0_5), .GE(co1_5));

    AGEB2 full_cmp_2 (.A0(wcount_4), .A1(wcount_5), .B0(rcount_w4), .B1(rcount_w5),
        .CI(co1_5), .GE(co2_5));

    AGEB2 full_cmp_3 (.A0(wcount_6), .A1(wcount_7), .B0(rcount_w6), .B1(r_g2b_xor_cluster_0),
        .CI(co2_5), .GE(co3_5));

    AGEB2 full_cmp_4 (.A0(wcount_8), .A1(wcount_9), .B0(rcount_w8), .B1(rcount_w9),
        .CI(co3_5), .GE(co4_5));

    AGEB2 full_cmp_5 (.A0(full_cmp_set), .A1(scuba_vlo), .B0(full_cmp_clr),
        .B1(scuba_vlo), .CI(co4_5), .GE(full_d_c));

    FADD2B a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo),
        .CI(full_d_c), .COUT(), .S0(full_d), .S1());

    FADD2B ae_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), .B1(rden_i),
        .CI(scuba_vlo), .COUT(cmp_ci_2), .S0(), .S1());

    AGEB2 ae_cmp_0 (.A0(AmEmptyThresh[0]), .A1(AmEmptyThresh[1]), .B0(rcnt_reg_0),
        .B1(rcnt_reg_1), .CI(cmp_ci_2), .GE(co0_6));

    AGEB2 ae_cmp_1 (.A0(AmEmptyThresh[2]), .A1(AmEmptyThresh[3]), .B0(rcnt_reg_2),
        .B1(rcnt_reg_3), .CI(co0_6), .GE(co1_6));

    AGEB2 ae_cmp_2 (.A0(AmEmptyThresh[4]), .A1(AmEmptyThresh[5]), .B0(rcnt_reg_4),
        .B1(rcnt_reg_5), .CI(co1_6), .GE(co2_6));

    AGEB2 ae_cmp_3 (.A0(AmEmptyThresh[6]), .A1(AmEmptyThresh[7]), .B0(rcnt_reg_6),
        .B1(rcnt_reg_7), .CI(co2_6), .GE(co3_6));

    AGEB2 ae_cmp_4 (.A0(AmEmptyThresh[8]), .A1(AmEmptyThresh[9]), .B0(rcnt_reg_8),
        .B1(rcnt_reg_9), .CI(co3_6), .GE(co4_6));

    AGEB2 ae_cmp_5 (.A0(ae_setsig), .A1(scuba_vlo), .B0(ae_clrsig), .B1(scuba_vlo),
        .CI(co4_6), .GE(ae_d_c));

    FADD2B a2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo),
        .CI(ae_d_c), .COUT(), .S0(ae_d), .S1());

    FADD2B af_d_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i),
        .CI(scuba_vlo), .COUT(cmp_ci_3), .S0(), .S1());

    AGEB2 af_d_cmp_0 (.A0(wcnt_reg_0), .A1(wcnt_reg_1), .B0(AmFullThresh[0]),
        .B1(AmFullThresh[1]), .CI(cmp_ci_3), .GE(co0_7));

    AGEB2 af_d_cmp_1 (.A0(wcnt_reg_2), .A1(wcnt_reg_3), .B0(AmFullThresh[2]),
        .B1(AmFullThresh[3]), .CI(co0_7), .GE(co1_7));

    AGEB2 af_d_cmp_2 (.A0(wcnt_reg_4), .A1(wcnt_reg_5), .B0(AmFullThresh[4]),
        .B1(AmFullThresh[5]), .CI(co1_7), .GE(co2_7));

    AGEB2 af_d_cmp_3 (.A0(wcnt_reg_6), .A1(wcnt_reg_7), .B0(AmFullThresh[6]),
        .B1(AmFullThresh[7]), .CI(co2_7), .GE(co3_7));

    AGEB2 af_d_cmp_4 (.A0(wcnt_reg_8), .A1(wcnt_reg_9), .B0(AmFullThresh[8]),
        .B1(AmFullThresh[9]), .CI(co3_7), .GE(co4_7));

    AGEB2 af_d_cmp_5 (.A0(wcnt_reg_10), .A1(scuba_vlo), .B0(scuba_vlo),
        .B1(scuba_vlo), .CI(co4_7), .GE(af_d_c));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B a3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo),
        .CI(af_d_c), .COUT(), .S0(af_d), .S1());

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute pdp_ram_0_0_3 MEM_LPC_FILE fifo_dc_efb.lpc
    // exemplar attribute pdp_ram_0_0_3 MEM_INIT_FILE
    // exemplar attribute pdp_ram_0_1_2 MEM_LPC_FILE fifo_dc_efb.lpc
    // exemplar attribute pdp_ram_0_1_2 MEM_INIT_FILE
    // exemplar attribute pdp_ram_0_2_1 MEM_LPC_FILE fifo_dc_efb.lpc
    // exemplar attribute pdp_ram_0_2_1 MEM_INIT_FILE
    // exemplar attribute pdp_ram_0_3_0 MEM_LPC_FILE fifo_dc_efb.lpc
    // exemplar attribute pdp_ram_0_3_0 MEM_INIT_FILE
    // exemplar attribute FF_135 GSR ENABLED
    // exemplar attribute FF_134 GSR ENABLED
    // exemplar attribute FF_133 GSR ENABLED
    // exemplar attribute FF_132 GSR ENABLED
    // exemplar attribute FF_131 GSR ENABLED
    // exemplar attribute FF_130 GSR ENABLED
    // exemplar attribute FF_129 GSR ENABLED
    // exemplar attribute FF_128 GSR ENABLED
    // exemplar attribute FF_127 GSR ENABLED
    // exemplar attribute FF_126 GSR ENABLED
    // exemplar attribute FF_125 GSR ENABLED
    // exemplar attribute FF_124 GSR ENABLED
    // exemplar attribute FF_123 GSR ENABLED
    // exemplar attribute FF_122 GSR ENABLED
    // exemplar attribute FF_121 GSR ENABLED
    // exemplar attribute FF_120 GSR ENABLED
    // exemplar attribute FF_119 GSR ENABLED
    // exemplar attribute FF_118 GSR ENABLED
    // exemplar attribute FF_117 GSR ENABLED
    // exemplar attribute FF_116 GSR ENABLED
    // exemplar attribute FF_115 GSR ENABLED
    // exemplar attribute FF_114 GSR ENABLED
    // exemplar attribute FF_113 GSR ENABLED
    // exemplar attribute FF_112 GSR ENABLED
    // exemplar attribute FF_111 GSR ENABLED
    // exemplar attribute FF_110 GSR ENABLED
    // exemplar attribute FF_109 GSR ENABLED
    // exemplar attribute FF_108 GSR ENABLED
    // exemplar attribute FF_107 GSR ENABLED
    // exemplar attribute FF_106 GSR ENABLED
    // exemplar attribute FF_105 GSR ENABLED
    // exemplar attribute FF_104 GSR ENABLED
    // exemplar attribute FF_103 GSR ENABLED
    // exemplar attribute FF_102 GSR ENABLED
    // exemplar attribute FF_101 GSR ENABLED
    // exemplar attribute FF_100 GSR ENABLED
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
