/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.8 */
/* Sun Aug 25 10:58:03 2019 */

/* parameterized module instance */
fifo_dc_efb __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .AmEmptyThresh( ), .AmFullThresh( ), .Q( ), 
    .Empty( ), .Full( ), .AlmostEmpty( ), .AlmostFull( ));
